// Kategori program studi
export const KATEGORI_PRODI = [
  { id: "semua", label: "Semua" },
  { id: "sains-teknologi", label: "Sains & Teknologi" },
  { id: "sosial-humaniora", label: "Sosial & Humaniora" },
  { id: "kesehatan", label: "Kesehatan" },
  { id: "ekonomi-bisnis", label: "Ekonomi & Bisnis" },
  { id: "pendidikan", label: "Pendidikan" },
  { id: "hukum", label: "Hukum" },
  { id: "seni-desain", label: "Seni & Desain" },
];

// Data contoh program studi
export const DATA_PRODI = [
  {
    id: "teknik-informatika-ui",
    nama: "Teknik Informatika",
    universitas: "Universitas Indonesia",
    akronim: "UI",
    kategori: "sains-teknologi",
    slug: "teknik-informatika-ui",
    passing_grade: 82.5,
    daya_tampung: 120,
    peminat: 4500,
    keketatan: "Sangat Ketat",
    rating: 4.8,
    ulasan: 234,
    akreditasi: "Unggul",
    lokasi: "Depok, Jawa Barat",
    prospek: ["Software Engineer", "Data Scientist", "AI Engineer", "CTO"],
    deskripsi: "Program studi terbaik di Indonesia untuk bidang komputasi, AI, dan rekayasa perangkat lunak.",
    kurikulum: ["Algoritma", "Struktur Data", "Machine Learning", "Web Development"],
    biaya: 12500000,
    gambar: null,
  },
  {
    id: "kedokteran-ugm",
    nama: "Kedokteran",
    universitas: "Universitas Gadjah Mada",
    akronim: "UGM",
    kategori: "kesehatan",
    slug: "kedokteran-ugm",
    passing_grade: 91.2,
    daya_tampung: 90,
    peminat: 8200,
    keketatan: "Sangat Ketat",
    rating: 4.9,
    ulasan: 412,
    akreditasi: "Unggul",
    lokasi: "Yogyakarta",
    prospek: ["Dokter Umum", "Dokter Spesialis", "Peneliti Medis"],
    deskripsi: "Salah satu sekolah kedokteran terbaik Asia Tenggara dengan kurikulum internasional.",
    kurikulum: ["Anatomi", "Fisiologi", "Patologi", "Klinik"],
    biaya: 15000000,
    gambar: null,
  },
  {
    id: "hukum-ui",
    nama: "Ilmu Hukum",
    universitas: "Universitas Indonesia",
    akronim: "UI",
    kategori: "hukum",
    slug: "hukum-ui",
    passing_grade: 79.8,
    daya_tampung: 200,
    peminat: 5600,
    keketatan: "Ketat",
    rating: 4.6,
    ulasan: 189,
    akreditasi: "Unggul",
    lokasi: "Depok, Jawa Barat",
    prospek: ["Pengacara", "Hakim", "Notaris", "Konsultan Hukum"],
    deskripsi: "Program hukum dengan reputasi terbaik yang melahirkan praktisi dan akademisi hukum terkemuka.",
    kurikulum: ["Hukum Perdata", "Hukum Pidana", "Hukum Tata Negara", "Hukum Internasional"],
    biaya: 10000000,
    gambar: null,
  },
  {
    id: "manajemen-feb-ui",
    nama: "Manajemen",
    universitas: "Universitas Indonesia (FEB)",
    akronim: "UI",
    kategori: "ekonomi-bisnis",
    slug: "manajemen-feb-ui",
    passing_grade: 78.3,
    daya_tampung: 180,
    peminat: 6100,
    keketatan: "Ketat",
    rating: 4.7,
    ulasan: 302,
    akreditasi: "Unggul",
    lokasi: "Depok, Jawa Barat",
    prospek: ["Manajer", "Konsultan Bisnis", "Wirausahawan", "Bankir"],
    deskripsi: "Fakultas ekonomi dan bisnis terkemuka dengan jaringan alumni yang kuat di dunia korporat.",
    kurikulum: ["Manajemen Keuangan", "Marketing", "SDM", "Strategi Bisnis"],
    biaya: 11000000,
    gambar: null,
  },
  {
    id: "arsitektur-itb",
    nama: "Arsitektur",
    universitas: "Institut Teknologi Bandung",
    akronim: "ITB",
    kategori: "seni-desain",
    slug: "arsitektur-itb",
    passing_grade: 83.7,
    daya_tampung: 80,
    peminat: 3200,
    keketatan: "Sangat Ketat",
    rating: 4.8,
    ulasan: 167,
    akreditasi: "Unggul",
    lokasi: "Bandung, Jawa Barat",
    prospek: ["Arsitek", "Urban Planner", "Interior Designer", "Kontraktor"],
    deskripsi: "Program arsitektur terbaik di Indonesia dengan pendekatan desain yang inovatif dan berkelanjutan.",
    kurikulum: ["Studio Desain", "Teknologi Struktur", "Sejarah Arsitektur", "Urban Design"],
    biaya: 13000000,
    gambar: null,
  },
  {
    id: "psikologi-ugm",
    nama: "Psikologi",
    universitas: "Universitas Gadjah Mada",
    akronim: "UGM",
    kategori: "sosial-humaniora",
    slug: "psikologi-ugm",
    passing_grade: 76.4,
    daya_tampung: 150,
    peminat: 4800,
    keketatan: "Ketat",
    rating: 4.6,
    ulasan: 221,
    akreditasi: "Unggul",
    lokasi: "Yogyakarta",
    prospek: ["Psikolog Klinis", "HRD", "Konselor", "Peneliti"],
    deskripsi: "Jurusan psikologi dengan akreditasi unggul dan laboratorium lengkap untuk praktik mahasiswa.",
    kurikulum: ["Psikologi Klinis", "Psikologi Industri", "Psikodiagnostik", "Neuropsikologi"],
    biaya: 8500000,
    gambar: null,
  },
];
