// Daftar subtes UTBK-SNBT beserta konfigurasi
export const SUBTES_LIST = [
  {
    id: "pu",
    nama: "Penalaran Umum",
    singkatan: "PU",
    jumlahSoal: 30,
    waktu: 45, // menit
    icon: "brain",
    deskripsi: "Mengukur kemampuan bernalar, menganalisis, dan menyimpulkan informasi",
    warna: "#7c3aed",
    paketLatihan: 3,
    materiTersedia: 7,
  },
  {
    id: "ppu",
    nama: "Pengetahuan dan Pemahaman Umum",
    singkatan: "PPU",
    jumlahSoal: 20,
    waktu: 30,
    icon: "globe",
    deskripsi: "Mengukur pengetahuan umum dan pemahaman tentang berbagai bidang ilmu",
    warna: "#6d28d9",
    paketLatihan: 2,
    materiTersedia: 7,
  },
  {
    id: "pbm",
    nama: "Pemahaman Bacaan dan Menulis",
    singkatan: "PBM",
    jumlahSoal: 20,
    waktu: 25,
    icon: "bookOpen",
    deskripsi: "Mengukur kemampuan membaca, memahami teks, dan keterampilan menulis",
    warna: "#5b21b6",
    paketLatihan: 2,
    materiTersedia: 7,
  },
  {
    id: "pk",
    nama: "Pengetahuan Kuantitatif",
    singkatan: "PK",
    jumlahSoal: 20,
    waktu: 20,
    icon: "calculator",
    deskripsi: "Mengukur kemampuan berhitung, interpretasi data kuantitatif",
    warna: "#4c1d95",
    paketLatihan: 3,
    materiTersedia: 7,
  },
  {
    id: "lbi",
    nama: "Literasi Bahasa Indonesia",
    singkatan: "LBI",
    jumlahSoal: 30,
    waktu: 45,
    icon: "fileText",
    deskripsi: "Mengukur kemampuan literasi bahasa Indonesia secara kritis",
    warna: "#6d28d9",
    paketLatihan: 2,
    materiTersedia: 7,
  },
  {
    id: "lbing",
    nama: "Literasi Bahasa Inggris",
    singkatan: "LBIng",
    jumlahSoal: 20,
    waktu: 30,
    icon: "languages",
    deskripsi: "Mengukur kemampuan memahami teks bahasa Inggris secara kritis",
    warna: "#7c3aed",
    paketLatihan: 2,
    materiTersedia: 7,
  },
  {
    id: "pm",
    nama: "Penalaran Matematika",
    singkatan: "PM",
    jumlahSoal: 20,
    waktu: 30,
    icon: "sigma",
    deskripsi: "Mengukur kemampuan penalaran matematis dan pemecahan masalah",
    warna: "#5b21b6",
    paketLatihan: 2,
    materiTersedia: 7,
  },
];

// Paket Try Out lengkap
export const PAKET_TRYOUT = [
  {
    id: "to-1",
    nama: "Try Out UTBK Paket 1",
    deskripsi: "Simulasi lengkap UTBK-SNBT mencakup semua subtes dengan pengacakan soal otomatis",
    totalSoal: 140,
    totalWaktu: 205, // menit
    tingkatKesulitan: "Sedang",
    badge: "Populer",
    subtes: ["pu", "ppu", "pbm", "pk", "lbi", "lbing", "pm"],
  },
  {
    id: "to-2",
    nama: "Try Out UTBK Paket 2",
    deskripsi: "Paket simulasi dengan tingkat kesulitan lebih tinggi mendekati soal UTBK asli",
    totalSoal: 140,
    totalWaktu: 205,
    tingkatKesulitan: "Sulit",
    badge: "Baru",
    subtes: ["pu", "ppu", "pbm", "pk", "lbi", "lbing", "pm"],
  },
  {
    id: "to-3",
    nama: "Try Out UTBK Paket 3",
    deskripsi: "Paket latihan intensif khusus untuk pendalaman materi tes kognitif",
    totalSoal: 140,
    totalWaktu: 205,
    tingkatKesulitan: "Mudah",
    badge: null,
    subtes: ["pu", "ppu", "pbm", "pk", "lbi", "lbing", "pm"],
  },
];
